version: "3"

services:
    php:
        container_name: automat-php
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
        networks:
            - automat
    nginx:
        container_name: automat-nginx
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
        ports:
            - 8080:80
        networks:
            - automat
        env_file:
            - .env.nginx.local

volumes:
    symfony_app_var:
    symfony_app_vendor:

networks:
    automat:
